CREATE TABLE categoria (
    ID_CATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
    Categoria Varchar(25)
);

CREATE TABLE estrelas (
    ID_STAR INT AUTO_INCREMENT PRIMARY KEY,
    AVALIACAO VARCHAR (45)
);

CREATE TABLE avaliacoes (
    ID_AVALIACAO INT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO TEXT
);

CREATE TABLE obras (
    ID_OBRA INT AUTO_INCREMENT PRIMARY KEY,
    Nome Varchar(50),
    Lancamento Date,
    Autor Varchar(30),
    ID_CATEGORIA INT,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES categoria(ID_CATEGORIA),
    ID_AVALIACAO INT,
    FOREIGN KEY (ID_AVALIACAO) REFERENCES avaliacoes(ID_AVALIACAO),
    Sinopse text,
    ID_STAR INT,
    FOREIGN KEY (ID_STAR) REFERENCES estrelas(ID_STAR),
    Foto varchar(255),
    Tipo INT
);

